name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas
  workflow_dispatch:  # Para acionar manualmente

permissions:
  contents: write  # Permissão para gravar conteúdos

jobs:
  build:
    name: jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate snake
        run: |
          git clone https://github.com/Platane/snk.git
          cd snk
          npm install
          npm run generate -- --github-user-name Ary-pedro --output dist/github-contribution-grid-snake.svg

      - uses: peaceiris/actions-gh-pages@2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
