name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas
  workflow_dispatch:  # Para acionar manualmente

jobs:
  build:
    name: jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Ary-pedro
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
         GITHUB_TOKEN_PERMISSIONS: write
